"use client";

import { Footer } from '@mantine/core';
import { FooterSimple } from '../../components/Footer';
import { HeaderMegaMenu } from '../../components/Navbar';
import Providers from './providers';
import { GPAContextProvider } from './contexts/gpaContext';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <GPAContextProvider>
        <html lang="en">

          <body>
            <HeaderMegaMenu />
            {children}
            <FooterSimple />
          </body>
        </html>
      </GPAContextProvider>
    </Providers>
  )
}
